Finished header component
teamtaverna/web_client pull request #40
Opened 2017-01-13 18:02 UTC by andela-akolawole

This PR transform the header html in the static_build to a react component.

![header](https://cloud.githubusercontent.com/assets/16742431/21940014/9ce9bea4-d9c2-11e6-965b-514810caeb4d.png)

2017-01-13 23:51 UTC, abiodun0 requested changes
I see no tests!.. Please write comprehensive tests for each and every of this components

2017-01-15 01:55 UTC, abiodun0 commented on src/components/icons/index.js
> +export { default as ExpandIcon } from './expandIcon/expandIcon';
Dont use this format. Use as it was written before i.e
```javascript
export ExpandIcon from './expandIcon/expandIcon'
````

2017-01-15 01:55 UTC, abiodun0 commented on src/components/index.js
> +export { default as Sample } from './sample/sample';
Same comment as above

2017-01-15 01:56 UTC, abiodun0 commented on src/components/sample/sample.test.jsx
> +    const sample = render(<Sample />);
Shallow rendering would do here.. if it's to contain you are checking for here. it's faster and doesn't render the full dom.

2017-01-15 01:57 UTC, abiodun0 commented on src/components/selector/selector.scss
> +      width: 100%;
Don't use magic numbers. if you are using any literals make it avaialble inside the _variables.css with their unique variable names

2017-01-15 01:59 UTC, abiodun0 requested changes
Some minor changes to make :)

2017-01-15 15:14 UTC, abiodun0 approved these changes

2017-01-15 15:18 UTC, andela-rsadiq commented
@andela-akolawole Could you give an overview/summary of what this PR does as a body attached to the PR itself? Also, there seems to be a lot of files change for one PR. Could you possibly break it down to small units of implementation? I would be closing this PR to allow for you to make these correction. Thanks

2017-01-15 15:18 UTC, closed without merging