Menu Page Layout
teamtaverna/web_client pull request #57
Opened 2017-02-21 10:10 UTC by andela-akolawole

### What does this PR do?
This creates a default HTML markup for other components

### Related Issue
#53

2017-02-22 11:09 UTC, uzoawili requested changes

2017-02-22 11:09 UTC, andela-uawili commented on src/components/menu_page_layout/menuPageLayout.jsx
> +              {/* <svg class="tvn icon"><use xlink:href="#icon-taverna"></use></svg>*/}
In the spirit of keeping to our coding standards, let's remove this commented code (I know we agreed to leave it there for a reason).

2017-02-22 11:16 UTC, andela-akolawole commented
@andela-uawili Fixed

2017-02-24 21:42 UTC, andela-ashuaib commented on src/components/logo/logo.jsx
> +const Logo = props => (
if you are open to it not critcal but destructring would be more succint here

```javascript 
const Logo = ({organizationName}) =>
```

2017-02-24 21:43 UTC, uzoawili approved these changes

2017-02-24 21:43 UTC, merged